// <auto-generated />
using ClassLibrary.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClassLibrary.Migrations
{
    [DbContext(typeof(WebServiceContext))]
    partial class WebServiceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClassLibrary.Models.Airport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Airline")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAirport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Airports", (string)null);
                });

            modelBuilder.Entity("ClassLibrary.Models.CodeAirport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AirportId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AirportId");

                    b.ToTable("CodeAirports", (string)null);
                });

            modelBuilder.Entity("ClassLibrary.Models.DepartureAndArrival", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AirportId")
                        .HasColumnType("int");

                    b.Property<string>("Arrival")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Departure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Distance")
                        .HasColumnType("int");

                    b.Property<string>("Routing")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AirportId");

                    b.ToTable("DeparturesAndArrivals", (string)null);
                });

            modelBuilder.Entity("ClassLibrary.Models.Information", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AirportId")
                        .HasColumnType("int");

                    b.Property<string>("NumberBoard")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberFlight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AirportId")
                        .IsUnique()
                        .HasFilter("[AirportId] IS NOT NULL");

                    b.ToTable("Informations", (string)null);
                });

            modelBuilder.Entity("ClassLibrary.Models.PitStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AirportId")
                        .HasColumnType("int");

                    b.Property<int?>("DepAndArrId")
                        .HasColumnType("int");

                    b.Property<string>("PitStopCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PitStopDuration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AirportId");

                    b.HasIndex("DepAndArrId");

                    b.ToTable("PitStops", (string)null);
                });

            modelBuilder.Entity("ClassLibrary.Models.CodeAirport", b =>
                {
                    b.HasOne("ClassLibrary.Models.Airport", "Airport")
                        .WithMany("CodeAirports")
                        .HasForeignKey("AirportId");

                    b.Navigation("Airport");
                });

            modelBuilder.Entity("ClassLibrary.Models.DepartureAndArrival", b =>
                {
                    b.HasOne("ClassLibrary.Models.Airport", "Airport")
                        .WithMany("DepartureAndArrivals")
                        .HasForeignKey("AirportId");

                    b.Navigation("Airport");
                });

            modelBuilder.Entity("ClassLibrary.Models.Information", b =>
                {
                    b.HasOne("ClassLibrary.Models.Airport", "Airport")
                        .WithOne("Information")
                        .HasForeignKey("ClassLibrary.Models.Information", "AirportId");

                    b.Navigation("Airport");
                });

            modelBuilder.Entity("ClassLibrary.Models.PitStop", b =>
                {
                    b.HasOne("ClassLibrary.Models.Airport", "Airport")
                        .WithMany("PitStops")
                        .HasForeignKey("AirportId");

                    b.HasOne("ClassLibrary.Models.DepartureAndArrival", "DepartureAndArrival")
                        .WithMany("PitStops")
                        .HasForeignKey("DepAndArrId");

                    b.Navigation("Airport");

                    b.Navigation("DepartureAndArrival");
                });

            modelBuilder.Entity("ClassLibrary.Models.Airport", b =>
                {
                    b.Navigation("CodeAirports");

                    b.Navigation("DepartureAndArrivals");

                    b.Navigation("Information");

                    b.Navigation("PitStops");
                });

            modelBuilder.Entity("ClassLibrary.Models.DepartureAndArrival", b =>
                {
                    b.Navigation("PitStops");
                });
#pragma warning restore 612, 618
        }
    }
}
